### ISSUE TITLE
Jeśli robimy odległość na sztywno to na pełną sekcję, a nie pojedynczy element. Tu padding powinien być na .header

### ISSUE THREAD

**Issue by ajotka** [Bebeto9009/portfolio_ap#1]
https://github.com/Bebeto9009/portfolio_ap/blob/4929842a3ad3fc4088d5e989e7f2493bc7ae2418/src/css/styles.scss#L181

**Comment by pawlakadrian** [comment]
poprawiłem, dając padding na .header
